### ISSUE TITLE
Argumentos passthrough en funciones del tipo _iterator

### ISSUE THREAD

**Issue by rcomesan** [sisoputnfrba/so-commons-library#110]
Estaría bueno poder contar con un argumento passthrough que se pase directamente a los callbacks calleados por funciones del tipo _iterator para poder branchear o aplicar comportamiento dependiente del argumento pasado dentro del mismo callback.

Por ejemplo, en el caso de dictionary_iterator. Si uno tiene que hacer una copia de cada elemento del diccionario a otra estructura, cómo sabe el callback cuál es el destino de esa copia si sólo recibe una key (char*) y un value (void*)?

O por ejemplo, si necesitamos filtrarlos, como le hago saber al callback los argumentos variantes de mi filtro?

Sí, puedo usar una variable global para esto, o también podría ponerlo dentro del value que contiene el dict... pero no tiene mucho sentido.

O directamente proveer un método alternativo de iteración sin el uso de un callback.

**Comment by mgarciaisaia** [comment]
¡Aloha!

Hemos hablado largo y tendido sobre cómo usar las funciones de orden superior de las commons - casi que todos los cuatris surgen dudas al respecto. De hecho, el año pasado [grabé un video al respecto](https://www.youtube.com/watch?v=1kYyxZXGjp0).

Me queda preguntarte cuánto creés que entendiste de todo eso, y si se te ocurren: a) cómo quedaría la interfaz de las funciones en el escenario que proponés/imaginás; b) cómo sería una posible implentación de las mismas; c) cuán segur@ estás de que es una implementación posible y viable.

En otras palabras, no termino de entender si estás intentando entender cómo usar las funciones de orden superior, o si te resultan medio incómodas, o si tenés en la cabeza una posible implementación pensada con cierto grado de confianza de que sea implementable.

Contame, así vemos hasta dónde podemos llegar con esto :)

¡Un abrazo!

**Comment by rcomesan** [comment]
Hola, gracias por tu atención. Me refiero a que la API es limitante.

dictionary_iterator no es realmente un iterator, es un traverse o un for each. En tal caso, debería soportar un argumento extra (passthrough) para poder yo como usuario enviarle información adicional a mi callback (función a visitar para cada key-value pair del diccionario). La mayoría de las funciones de este tipo se implementan así, por ejemplo:

- https://developer.gnome.org/glib/stable/glib-Hash-Tables.html#g-hash-table-foreach
- https://developer.gnome.org/glib/stable/glib-Balanced-Binary-Trees.html#g-tree-traverse
- https://github.com/fmela/libdict/blob/master/src/hashtable.c#L267

Y alternativamente proveer un iterator real que permita iterar (sin el uso de un callback) cada entrada del diccionario.

Una posible api mínima podría ser:

- void dictionary_iter_init(dictionary_t* _self) o void dictionary_iter_first(dictionary_t* _self)
- bool dictionary_iter_next(dictionary_t* _self, const char* _outKey, void* _outValue)

**Comment by gastonprieto** [comment]
Relacionado con #80
