### ISSUE TITLE
Problema con funcion string_to_upper

### ISSUE THREAD

**Issue by facuhump2409** [sisoputnfrba/so-commons-library#111]
hola estoy teniendo problemas para usar la funcion string to upper de las commons. Sin importar como le pase el string me tira siempre el mismo error.
![Screenshot from 2019-05-20 18-18-43](https://user-images.githubusercontent.com/32522610/58052640-c460d000-7b2b-11e9-86af-832a33fc0799.png)

Queria saber porque podia ser? Mas que nada queria usar la funcion para verificar el tema de la existencia de tablas, como pide el enunciado en UPPERCASE

Muchas gracias

**Comment by mgarciaisaia** [comment]
> Sin importar como le pase el string me tira siempre el mismo error.

Ahí desconfío, eh. ¿Nos compartís un ejemplo?

La función "anda". O, buen, al menos existe [_al menos un caso_](https://github.com/sisoputnfrba/so-commons-library/blob/0944b25908c0efa9e19d31f8046028749a8812c4/tests/unit-tests/test_string.c#L79-L86) en el que funciona bien. Capaz se nos escapó alguno, pero también es medio falso eso de que no importa cómo la uses, siempre falla.

Mostranos cómo estás consiguiendo el valor que le pasás a la función, para ver qué está pasando. Mis corazonadas son que: a) falta un `\0` en tu cadena de caracteres; o b) tu string es un literal (que está en el segmento de código del programa) y entonces no puede ser asignado. Apuesto más a la segunda, pero queremos asegurarnos de las cosas en vez de andar timbeando.

**Comment by facuhump2409** [comment]
![Screenshot from 2019-05-20 19-18-29](https://user-images.githubusercontent.com/32522610/58056123-700f1d80-7b36-11e9-83fe-6a4befcfe1c4.png)
ahi son dos ejemplos que mando que ya estaba probando por probar para ver que funcione. Pero tambien le pase un "buffer" y me pasaba lo mismo, por eso empece a probar con esas dos formas tontas para ver si podia hacerla andar.

**Comment by mgarciaisaia** [comment]
@facuhump2409 fijate si tenés acceso a [este viejo post del Campus Virtual](https://www.campusvirtual.frba.utn.edu.ar/especialidad/mod/forum/discuss.php?d=26065#p67359).

Si no, acá lo transcribo para futuras generaciones:

> El problema que tiene esto es que `string_append` **modifica** el primer parámetro que recibe, pero los strings literales (como el `"HOLA "` que está por ahí) se guardan en el segmento de código del programa, por lo que son de sólo lectura.
>
> Durante la primer jornada de charlas en Medrano, no recuerdo por qué motivo pero nos surgió una duda al respecto con los chicos, y lo pude probar con un programa como lo que hay acá: https://gist.github.com/mgarciaisaia/fd5e97ad36d7ff018aa4
>
> Fijate cómo hay tres grupos de direcciones perfectamente bien distinguidos: hay un montón de direcciones de la pinta `0x10c4d1???`, otras en `0x7fff5372e8??`, y otra (la del heap) en `0x7fdc78c03a20`.
>
> Fijate, por ejemplo, que la variable local de la `funcionUno` da exactamente la misma dirección que la `funcionDos`. Es pura casualidad, sí. Pero no hay problema, porque para cuando yo llamé a la `funcionDos`, ya había terminado la ejecución de `funcionUno`. Y el parámetro, obviamente, está en direcciones cercanas. ¿Qué segmento será ese? Claro que sí, el stack.
>
> Las funciones están en direcciones como `0x10c4d1d??`. Osea, ese tiene que ser el segmento de código. Y, ¿quiénes más están ahí cerca? Los dos literales :) Osea, los literales se guardan en el segmento de código.
>
> Por último, la variable del `malloc` está en cualquier otro lado. No la variable que apunta al bloque de memoria que da `malloc()`, si no el bloque mismo. Ese bloque es el heap :)
>
> Si pensamos en los permisos que tenemos en cada segmento, entendemos por qué no podemos pasarle un literal a `string_append`: porque no puede modificar el segmento de código. Las alternativas son dos: o hacemos un array de caracteres (un `char[]`), que, como es una variable local, va a estar en el stack, o lo creamos en memoria dinámica, en el heap, usando `malloc()`. En ambos segmentos tenemos permisos de escritura :)
>
> Obviamente, si hacemos un array en el stack vamos a necesitar garantizar de algún modo que tengamos espacio suficiente, que no es trivial. Así que lo más probable es que usemos `malloc()`.
>
> Por otro lado, las commons ofrecen dos funciones más que te pueden ayudar con todo esto: `string_duplicate()`, que te devuelve una copia del string que le pases, pero en el heap, y `string_concat()`, que, en lugar de *modificar* el primer string que le pasás para agregarle el contenido del segundo, *crea un string nuevo* con el contenido concatenado de los otros dos.
>
> En la mayoría de los lenguajes de más alto nivel, los strings son inmutables: cada vez que uno concatena strings, se crea un nuevo string con el resultado de la concatenación. Tener objetos inmutables da una serie de propiedades bastante copadas para los programas, y por eso es que juegan a hacer eso.
