### ISSUE TITLE
Problema con config_set_value

### ISSUE THREAD

**Issue by PabloOve** [sisoputnfrba/so-commons-library#112]
Queríamos saber si esta era la forma correcta de utilizar el set value, ya que no nos actualiza el valor del archivo

![captura4](https://user-images.githubusercontent.com/31904880/59792029-b24c8b80-92a9-11e9-916d-ef639e789d66.png)

Así queda el archivo (size no actualizado)

![captura5](https://user-images.githubusercontent.com/31904880/59792181-f8095400-92a9-11e9-85c4-3d34c56516c7.png)

Estamos pasandole bien la ruta y el size es un char*, pero no se actualiza el valor

**Comment by gastoncastineira** [comment]
Buenas!

Un tanto tarde, lo sé, pero capaz te sirve todavía. Las dudas van en el foro porque de ese estamos más pendientes que lo que pueda surgir acá, nomás para que lo tengas en cuenta.

Sin entrar demasiado en la implementación, config no lee y escribe directamente sobre el archivo sino que lo hace sobre una estructura que mantiene en memoria para cachear toda la información. Para decirle a config que baje todos los cambios que hayas hecho con set al archivo, tenés que hacerlo mediante otra función que está en el .h de config llamada config_save

Saludos y éxitos!
