### ISSUE TITLE
Problema con el config_get_array_value

### ISSUE THREAD

**Issue by micayeza** [sisoputnfrba/so-commons-library#113]
Hola! estoy utillizando la función para levantar del archivo de configuracion un valor del tipo:
["192.168.1.4","92.168.0.4","127.0.0.1"]
Estoy casi segura de que lo había probado y me funcionaba bien, pero ahora lo que me trae en el array es:
pos 0 = "\"192.168.1.4\""
pos 1 =  "\"92.168.0.4\""
pos 2 = "\"127.0.0.1\""
A alguien más le pasa? siempre fue asi?
Gracias!

**Comment by mgarciaisaia** [comment]
¡Aloha!

No estoy seguro de estar entendiendo del todo el problema. ¿Es por las comillas?

Si así fuera, pensá cómo escribirías un campo de tipo string en el archivo de configuración. O fíjate [en los tests](https://github.com/sisoputnfrba/so-commons-library/blob/58f16f023da8c9fc6e92191146b73b326f690581/tests/unit-tests/resources/config.cfg).

**Comment by micayeza** [comment]
Hola! No se pego, pero el problema es que me trae **"\**"127.0.0.1"**\"**
Y no siempre... osea me esta concatenando una comilla y \ antes y despues, pero no en todos los casos tampoco

**Comment by gastonprieto** [comment]
Al final van sin las comillas.
