### ISSUE TITLE
Funciones faltantes en colecciones

### ISSUE THREAD

**Issue by rodr0m4** [sisoputnfrba/so-commons-library#116]
Buenas!

Recién haciendo algunas cosas del tp, me encontré con un par de cosas raras:

* La `queue` no tiene una interfaz similar a la lista, es bastante "boba" (no tiene operaciones de orden superior, por ejemplo), eso me llevó a implementar algo que es realmente una queue pero a veces quiero filtrar para convertir en otra queue como una lista :/

* Escribiendo código de este estilo:

```c
thread_t* next_to_run(process_t* self) {
  t_list* ready_queue = self->scheduling_data->ready;

  if (list_is_empty(ready_queue)) return NULL;

  return (thread_t*) list_fold(ready_queue, list_get(ready_queue, 0), __who_should_run_next);
}
```

Acá se ven algunos problemas de la lib:
* La lista tiene `fold` pero no `fold1`
* Tampoco tiene algunos foldeos más interesantes (`max_by`, `min_by`, etc.). 
* Tampoco tiene `first` y `last`. 

Son decisiones de diseño? o simplemente nadie se puso a escribirlas?

**Comment by gastonprieto** [comment]
Buenas!

Sobre la queue, si es una interfaz bastante simple porque ya que en general no son para recorrer, sino para dejar valores y luego sacarlos en cierto orden, entonces lo que podrías hacer es pasar de una queue a una lista (creo que podríamos este requerimiento) o podrías usar siempre una lista si necesitas orden e iteración.

Sobre el resto de las funciones de listas, cuando la hicimos pensamos en las funciones mas útiles que se nos ocurrieron, luego fuimos agregando y pueden faltar, así que cualquier PR con nuevas funcionalidades de ese estilo son bienvenidos :)

**Comment by RaniAgus** [comment]
Agregados `fold1`, `get_maximum` y `get_minimum` :)
