### ISSUE TITLE
Agregar una API simple para manejo de timestamps

### ISSUE THREAD

**Issue by RaniAgus** [sisoputnfrba/so-commons-library#156]
Podría ser algo simple que permita comparar dos timestamps:

```c
t_temporal *t1 = temporal_create();

// pasa un ratito...

t_temporal *t2 = temporal_create();

int64_t ms = temporal_diff(t2, t1);

temporal_destroy(t1);
temporal_destroy(t2);
```

O algo más complejo, parecido a un [`StopWatch`](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/time/StopWatch.html) de Apache Commons.

**Comment by julian-salinas** [comment]
Hola! Cómo va? Ví tu issue y se me ocurrio una forma de implementar esto que mencionás y desarrollé una solución en [un fork](https://github.com/julian-salinas/so-commons-library), si te parece, fijate si es en lo que estabas pensando :)

Mi idea fue crear una variable de tipo `t_temporal` que maneje milisegundos, sobre esa variable es posible obtener el tiempo desde que fué inicializada, calcular la diferencia con una variable del mismo tipo, poder pausarla y reanudarla cuando uno quiera.

saludos!

**Comment by RaniAgus** [comment]
¡Buenas @julian-salinas!

Genioo 🎉, mandanos un [Pull Request](https://github.com/sisoputnfrba/so-commons-library/compare/master...julian-salinas:so-commons-library:master?expand=1) y cuando tenga un ratito te hago code review 😉

También si podés subir un par de tests a [tests/integration-tests](https://github.com/sisoputnfrba/so-commons-library/tree/master/tests/integration-tests) con casos de uso simulados con `sleep`s a modo de ejemplo sería un golazo, se me ocurre algo tipo:

```c
void test_temporal_gettime() {
    t_temporal *temporal = temporal_create();
    sleep(2);
    temporal_stop(temporal);
    
    printf("test_temporal_gettime: %ldms (expected: ~2000ms)\n", temporal_gettime(temporal));

    temporal_destroy(temporal);
}


void test_temporal_resume() {
    // detendría y reiniciaría el temporal un par de veces
}


void test_temporal_diff() {
    // crearía 2 temporal, los detendría en distintos momentos y los compararía
}

// algún otro caso de uso?

int main() {
   test_temporal_gettime();
   test_temporal_resume();
   test_temporal_diff();
   ...
}
```

> _No los pondría en [tests/unit-tests](https://github.com/sisoputnfrba/so-commons-library/tree/master/tests/unit-tests) porque entiendo que es difícil hacerlo determinísitico, y si incluimos `sleeps` las pruebas tardarían bastante como para ser unitarias._

Abrazo

**Comment by julian-salinas** [comment]
Genial! Gracias Agus!
