### ISSUE TITLE
Cambiar el formato de la documentación

### ISSUE THREAD

**Issue by RaniAgus** [sisoputnfrba/so-commons-library#171]
Al parecer la docu no aparece en Visual Studio Code siguiendo el formato actual:

```c
	/**
	* @NAME: list_add
	* @DESC: Agrega un elemento al final de la lista
	*/
	int list_add(t_list *, void *element);
```

![image](https://user-images.githubusercontent.com/39303639/205798043-7fe312e6-c4b1-4ba9-83d6-5100e60b19bf.png)

Debemos elegir otro formato para hacer que aparezcan (por ejemplo, [doxygen](https://www.cs.cmu.edu/~410/doc/doxygen.html)):

```c
	/**
	* @brief Agrega un elemento al final de la lista
	* 
	* @param list puntero a la lista
	* @param element puntero al elemento a agregar
	* @return indice del elemento agregado
	*/
	int list_add(t_list *list, void *element);
```

![image](https://user-images.githubusercontent.com/39303639/204876584-b8272987-2bbc-4d3b-b7fb-14fd7a89ab2b.png)

**Comment by f-and** [comment]
Disculpen la molestia, pero de casualidad se sabe que programa se utilizó para generar la documentación vieja? La sintaxis que usa no aparece en ningún generador de documentación que encontré.

**Comment by mgarciaisaia** [comment]
La generamos a mano, con el autocompletado de Eclipse CDT. No sé si es un
formato estándar o es algo medio propio de Eclipse. Huele mucho a Javadoc.
