### ISSUE TITLE
Agregar forma de copiar las keys de un diccionario

### ISSUE THREAD

**Issue by papiness77** [sisoputnfrba/so-commons-library#180]
Estaria bueno eso, cuando creo un diccionario estaria bueno mandarle un diccionario ya creado y que el nuevo copie todas las keys del que se mando, copia las keys pero no los values

**Comment by RaniAgus** [comment]
Ya tenemos un método que retorna todas las keys de un diccionario en una lista, sin los values:

https://github.com/sisoputnfrba/so-commons-library/blob/72470a6732312c085185ae08d911e9f0d7c7fc1a/src/commons/collections/dictionary.h#L101-L105
