### ISSUE TITLE
list_find_element_and_index()

### ISSUE THREAD

**Issue by mgarciaisaia** [sisoputnfrba/so-commons-library#34]
Propusieron implementar esta función:

```
void* list_find_element_and_index(t_list *self, bool(*condition)(void*), int* index) {
    t_link_element *element = self->head;
    int position = 0;

    while (element != NULL && !condition(element->data)) {
        element = element->next;
        position++;
    }

    if (index != NULL) {
        *index = position;
    }

    return element != NULL ? element->data : NULL;
}
```

La idea es que busque un elemento que cumpla la condición y devuelva el índice en que se encuentra.

**Comment by RaniAgus** [comment]
No la decidí implementar aún porque no le veo ningún caso de uso: normalmente uno querría obtener el índice *para luego hacer otra cosa*, y para eso existen `find`, y `remove_by_condition`. La que faltaría sería:

```c
void list_replace_by_condition(t_list* self, void* element, bool(*condition)(void*));
```

El único caso que se me ocurre que no está tan bien contemplado es cuando "me quiero guardar el índice para en otro momento hacer un `remove` de ese elemento en la lista". Para eso, directamente me guardo al puntero y cuando quiera quitarlo de la lista hago algo como:

```c
void list_remove_element(t_list* self, void* element);
```

Esto es incluso es algo más seguro que guardar un índice, te previene de que la lista sea modificada y que el elemento que quieras mover no esté ahí. Sé puede hacer un `remove_by_condition` que le pase una inner function que compare ambos punteros, pero exponer esta opción puede ser más expresivo.

**Comment by mdumrauf** [comment]
Compro. Mi único comment sería modificar la firma para que sea consistente con `list_replace()`. `condition` estaría al nivel de `index` y `element` siempre al final, o al revés: https://github.com/sisoputnfrba/so-commons-library/blob/master/src/commons/collections/list.h#L108:L113

**Comment by RaniAgus** [comment]
En mi opinión, creo que aplicaría más la regla de dejar siempre los callbacks al final :P
