### ISSUE TITLE
Documentar mejor list_sort()

### ISSUE THREAD

**Issue by mgarciaisaia** [sisoputnfrba/so-commons-library#50]
Agregar a `list_sort()` algo de explicación sobre qué se espera del `comparator`.

**Comment by nachooantonuccio** [comment]
que se espera del comparador? necesito justo implementar la función para ordenar una lista y tengo esa duda

**Comment by mgarciaisaia** [comment]
[Acá hay un ejemplo](https://github.com/sisoputnfrba/so-commons-library/blob/master/tests/unit-tests/test_list.c#L266-L268).

Funciona _a la Smalltalk_: el comparador devuelve `true` si el primer parámetro tiene que aparecer en la lista antes que el segundo.

No estoy seguro de qué pasa en caso de igualdad (si los swappea o no).

**Comment by nachooantonuccio** [comment]
gracias por la pronta respuesta, me sirvió

saludos

2015-09-17 23:15 GMT-03:00 Matias Garcia Isaia <notifications@github.com>:
