### ISSUE TITLE
Explicar en README como Linkear una libreria desde Eclipse

### ISSUE THREAD

**Issue by francopesce** [sisoputnfrba/so-commons-library#52]
Para linkear una librería desde Eclipse:
1.En el Project Explorer (La columna de la izquierda), click derecho en tu proyecto que queres agregar la biblioteca > Properties > C/C++ Build > Settings > Tool Settings.
2.Hay vas a ver  GCC Linker > Libraries > Libraries (notar como dice -l, que es lo que estamos buscando).
3.Click en el botón de + y pones el nombre de la biblioteca, en este caso "commons" (sin el -l).

**Comment by mgarciaisaia** [comment]
[Biblioteca](https://github.com/manastech/handbook/pull/4) :)
