### ISSUE TITLE
Segfault en config_create cuando el archivo termina con dos \n

### ISSUE THREAD

**Issue by mgarciaisaia** [sisoputnfrba/so-commons-library#56]
Si el archivo de configuración a cargar con `config_create()` termina con dos newlines (`\n\n`), la función da segfault tratando de hacer un `string_split()`.

Eso no ocurre cuando el archivo tiene un doble newline en el medio.

Podría ocurrir que también rompa si no hay newlines al final. Lo vi recién con los chicos de @sisoputnfrba/plikiti-plikiti por su TP, estaría genial que nos aporten los archivos con los que están probando :)

**Comment by natiArgento** [comment]
dejo los archivos con los que estabamos probando, el primero es el que tiene los dos enter que hacia que se rompa. Si solo termina con un enter como el segundo archivo, no rompe.

```
# This is the IP
IP_MARTA=127.0.0.1

PUERTO_MARTA=6667

MAPPER=mapper.sh


REDUCE=reduce.sh

COMBINER=S

ARCHIVOS=[]

RESULTADO=user/juan/datos/temperatura-2012.txt


```

```PUERTO_FS=6667

IP_FS=127.0.0.1

ARCHIVO_BIN=data.bin

DIR_TEMP=/tmp

NODO_NUEVO=SI

IP_NODO=127.0.0.1

```
