### ISSUE TITLE
string_split se comporta de manera errática

### ISSUE THREAD

**Issue by mgarciaisaia** [sisoputnfrba/so-commons-library#57]
`string_split` devuelve resultados extraños en los casos en que el separador se encuentre al principio o al final del string origen. Debería comportarse como [String#split en Ruby](http://ruby-doc.org/core-2.2.0/String.html#method-i-split)

Viene de un mensaje de @emiiSierra en [el Campus Virtual](http://www.campusvirtual.frba.utn.edu.ar/especialidad/mod/forum/discuss.php?d=34841)

**Comment by emiiSierra** [comment]
Perdón, mala mía, sí funciona con el separador tanto al principio como al final del string. En mi código tenía el error en otra parte.

**Comment by mgarciaisaia** [comment]
Es cierto, el issue es otro. Ahí lo rewordeé, porque la verdad es que está horrible la función ^_^

**Comment by gastonprieto** [comment]
Su comportamiento no es erratico, es culpa de strtok, que el token inicial y final los ignora :P

**Comment by mgarciaisaia** [comment]
Sí, bueno, `strtok` puede irse a cocer a tapioca, yo necesito que `string_split` funcione como espero :)

**Comment by gastonprieto** [comment]
Definime como esperas, porque muchos mensajes la implementan distintos :P

**Comment by gastonprieto** [comment]
La más consistente me parece que es la de javascript

**Comment by gastonprieto** [comment]
### Javascript
```javascript
"".split("/")
[""]

"/path/foo".split("/")
["", "path", "foo"]

"/path/foo/".split("/")
["", "path", "foo", ""]
```

### Ruby
```ruby
"".split("/")
[]

"/path/foo".split("/")
["", "path", "foo"]

"/path/foo/".split("/")
["", "path", "foo"]
```

**Comment by mgarciaisaia** [comment]
Y este coincide en ambos:
```
"no tengo separador".split("/")
["no tengo separador"]
```

Me gustó más el de Javascript, ganaste. No se qué estará haciendo Ruby para decir que `"".split("/")` es distinto a `"hola".split("/")`, la verdad...

**Comment by RaniAgus** [comment]
#132 🚀 🚀
