### ISSUE TITLE
string_replacing

### ISSUE THREAD

**Issue by mgarciaisaia** [sisoputnfrba/so-commons-library#59]
Implementar una función `string_replacing` que reemplace todas las ocurrencias de un substring en una cadena por otro. La llamaría `string_replace` pero no debería mutar el original (o podríamos ofrecer las dos alternativas).

```
// returns a copy of source with all occurrences of pattern replaced by replacement
char *string_replacing(char *source, char *pattern, char *replacement);

string_replacing("hello", "ello", "ola") // devuelve "hola"
string_replacing("hello", "l", "") // devuelve "heo"
string_replacing("hello", "o", "o world!") // devuelve "hello world!"
string_replacing("hello", "not a substring", "yay!") // devuelve "hello"
string_replacing("hello", "", "x") // no tengo idea qué debería devolver - "hello"? "xhxexlxlxox"? NULL?
string_replacing("hello", NULL, "x") // error?
string_replacing(NULL, "a", "x") // devuelve NULL
```

No se si alguien lo va a usar en el TP, pero _yo_ lo voy a usar como una alternativa a `sed`/`awk`/`tr` en la consola - armando un comandito que aplique este reemplazo al stdin y lo escupa por stdout.

¿Opiniones, @gastonprieto?

**Comment by gastonprieto** [comment]
Por mi se podría hacer

El 10 de junio de 2015, 15:18, Matias Garcia Isaia <notifications@github.com
