### ISSUE TITLE
config_create() no acepta valores que contengan el caracter '='

### ISSUE THREAD

**Issue by jormaechea** [sisoputnfrba/so-commons-library#64]
Gist de ejemplo: https://gist.github.com/jormaechea/61522cfd28d5c8c9a582

**Comment by jormaechea** [comment]
Se debería hacer un 
`char** keyAndValue = string_n_split(line, 2, "=");`
en esta línea https://github.com/sisoputnfrba/so-commons-library/blob/master/src/commons/config.c#L48

**Comment by mgarciaisaia** [comment]
:+1: muy buena.
