### ISSUE TITLE
Problemas creando nuestra propia library

### ISSUE THREAD

**Issue by Trisky** [sisoputnfrba/so-commons-library#69]
Hola SO:

Estoy intentando hacer nuestra propia library para evitar código repetido entre procesos del TP.

Ya ví el video de como agregar una library que explica como usar las commos y el como crear una library(https://youtu.be/s5ac8CPDkMg). Las commons las puedo usar sin problemas haciendo #include <commons/asd.h>

Tengo esto:
En eclipse tengo un proyecto para cada proceso (planif, cpu, mem, swap) y un quinto proyecto libraryTP que lo creé siguiendo el vídeo ese que explica como agregar las commons al eclipse. libraryTP tiene el -fPIC.

En cada proyecto ya fui a c/c++ general> paths and symbols > library paths > add > /libraryTP (que está dentro del mismo workspace, que es mi root de github.

Cuando abro memoria.c  (ó el .c de cualquier proceso) e intento hacer #include <libraryTP/sockets.h> me dice que no puede resolver la inclusión.

Dentro de libraryTP en sockets.h tengo: 
```
#ifndef SOCKETS_H_
#define SOCKETS_H_

int escuchar(int puerto);
int conectarse(char* ip, int puerto);

#endif /* SOCKETS_H_ */
```

Que me falta? Gracias!

**Comment by mgarciaisaia** [comment]
@Trisky ¿Qué pasó que cerraste el issue? ¿Resolviste?
