### ISSUE TITLE
list_remove_and_destroy_by_condition borra un único elemento

### ISSUE THREAD

**Issue by ElianaLS** [sisoputnfrba/so-commons-library#73]
Hola! Haciendo el TP vi que si usaba el list_remove_and_destroy_by_condition solo me borraba el primer elemento que cumple con la condición (y como uno de los ayudantes me hizo saber después, es coherente, ya que llama al list_find_element que devuelve el primero que la cumple) pero la descripción del list_remove_and_destroy_by_condition  aún dice que saca todos los que cumplen la condición.
Me recomendaron que lo suba a issues para que lo tengan en cuenta!
Saludos

**Comment by mgarciaisaia** [comment]
Gracias por el aviso, ya lo corregí!
