### ISSUE TITLE
Agregar un parámetro data a algunas funciones de list.c y .h

### ISSUE THREAD

**Issue by julian-berbel** [sisoputnfrba/so-commons-library#77]
Para poder agregar información ajena al elemento a la condición.

Ejemplo del TP actual: 

Tengo una lista de estructuras consola que contienen el pid y el socket de la consola que representan. Teniendo un pid necesito obtener el socket correspondiente.

```
_Bool compararPid(t_consola* consola, int* pid){
    return consola->pid == *pid;
}

int unPid = 3;
t_consola* consola = list_find(consolas, compararPid, &unPid);
consola->socket;
```

Una posible forma para find y remove_and_destroy_by_condition: http://pastebin.com/45gHSqBi

Desde ya gracias

**Comment by julian-berbel** [comment]
Sepan disculpar la falta de labels. No tengo idea de como agregarlos...

**Comment by mgarciaisaia** [comment]
Los labels creo que los podemos agregar nosotros nomás.

Tenemos #72 esperando a que el bueno de @gastonprieto tenga ganas de revisarlo y mergear, en el que se muestra por qué no es tan necesario ese segundo parámetro.

Un motivo "a favor" de tu propuesta es que aplica la misma filosofía que `pthread_create`, por ejemplo. En vez de usar comportamiento exclusivo de `gcc`, usa C estándar, y permite flexibilidad. Pero no estoy muy seguro, tampoco.

Entré al issue para decir "no, ni a ganchos" y clavarle `wontfix` de una, peeeero "`pthread_create` funciona así" me parece un buen contra-argumento.

Me gustaría que opinen más gentes. ¿@sisoputnfrba/ayudantes?

**Comment by gastonprieto** [comment]
Sobre #72 ahí lo mergee :)

Sobre el uso de pasarle un argumento, en vez de aprovechar el scope de las variables, que es lo que se muestra en #72, no sé si es solo propio de gcc o no. Pero estoy a favor de este, porque debería ser código muy pequeño que pueda definirse en la misma función (hasta que algún día C tenga lambdas).

No creo que sea el mismo caso de ```pthread_create```, por varios motivos:
* Lo que hacen los hilos normalmente no es una función que hace poquito, sino que suele tener una _gran responsabilidad_.
* Recibe un argumento porque no puede aprovecharse siempre del scope, ```pthread_create``` crea un hilo que tiene su propio contexto, y si en realidad le pasaramos funciones que conocen variables del _scope_ local de la función que llama a ```pthread_create``` probablemente se rompa, porque una vez que retorne dicha función, lo que este ejecutando el hilo probablemente apunte a basura.

Por eso creo  que los que hicieron ```pthread_create``` *querían* pasarle un argumento extra, para que le pasen algo que sea independiente del contexto. En este caso las funciones son todas sincronicas así que no podría existir ese problema.

**Comment by julian-berbel** [comment]
Mindblown. Es la primera vez que veo que se puede definir una función dentro de otra en C.

Dejo el issue abierto por si quieren continuar con el debate pero ya mi problema está solucionado.

Muchas gracias!

**Comment by mgarciaisaia** [comment]
> Mindblown

Been there, done that.

@gastonprieto sí, las [nested functions](https://gcc.gnu.org/onlinedocs/gcc/Nested-Functions.html) son una extensión de `gcc`. Si llegaras a hacer una pregunta sobre nested functions en StackOverflow, los talibanes de C te van a mirar horrible.

Peeeeero sí que son bonitas - y tienen un efecto _wow_ hermoso como el que acaba de demostrar el compañero Julián.

No se qué decirte, che.

**Comment by gastonprieto** [comment]
Por ahora no me calentaría, los talibanes de C no les interesan nuestras discusiones en español.

Y realmente me parece una buena idea usarlas, la mayoría de los lenguajes actuales soportan ideas similares, y dado que es una biblioteca para uso educativo, dejaría las cosas así. :+1:
