### ISSUE TITLE
Soportar un iterador de listas externo

### ISSUE THREAD

**Issue by gastonprieto** [sisoputnfrba/so-commons-library#80]
Operaciones que tiene que entender:
- hasNext()
- next()
- remove()

Relacionado con #78

**Comment by MaximilianoFelice** [comment]
¿Por qué el remove?

Una implementación de colecciones puede tranquilamente no permitir eliminar un elemento. A lo sumo, tendríra que saber liberarlos al destruir el array, que no es lo mismo.

Lo que sí veo que es necesario es un `add()`.

**Comment by mgarciaisaia** [comment]
Es un iterador de _listas_, no un iterador genérico de colecciones - no veo por qué no soportar el `remove()`.

Por implementar el iterador o no - me da lo mismo ¯\\\_(ツ)_/¯

**Comment by RaniAgus** [comment]
Agregado en #127
