### ISSUE TITLE
Soportar/detectar saltos de línea de Windows en t_config

### ISSUE THREAD

**Issue by mgarciaisaia** [sisoputnfrba/so-commons-library#83]
El TAD de config tiene problemas con los saltos de línea Windows-like, pero es un error relativamente común en el código de los TPs.

_Técnicamente_ hablando quizá no sea lo más correcto, pero, dado el objetivo principal de la biblioteca, estaría bueno detectar esos casos y mostrar un warning al usuario, o bien soportar indistintamente ambos saltos de línea.

Podemos asumir que la biblioteca es nativa de Linux (y buscar los de Windows específicamente), o buscar hacer que detecte saltos "foráneos" (es decir, distintos al de la plataforma actual) dinámicamente.

**Comment by gastonprieto** [comment]
Entiendo el problema, pero no me suena que sea un problema de la biblioteca, me parece que deberíamos tener un link que explique el problema, y capaz linkearlo desde algún lado. Capaz detectarlo y tirar un warning con el link a ese documento.

Este problema les va a suceder en muchos lenguajes, creo que es mas sano que aprendan sobre el problema y sus posibles soluciones, a que la herramienta lo detecte automáticamente.

**Comment by mgarciaisaia** [comment]
Compro que no es necesario solucionarlo (y, quizá incluso, puede que sea _nocivo_ solucionarlo), pero detectarlo e informarlo es un must.

Me gusta la propuesta de escribir algo.
