### ISSUE TITLE
Feature Request: List sorting

### ISSUE THREAD

**Issue by tferraro** [sisoputnfrba/so-commons-library#99]
Podríamos tener un `list_t * list_sort(t_list*, int (*sorter)(void*))`, que nos devuelva la lista ordenada según un criterio, como lo ven?

**Comment by gastonprieto** [comment]
Vos decís porque la que está tiene efecto?

**Comment by tferraro** [comment]
Claro, como para que pegue con las de map y filter.

Lo veo como algo distante igual, tenemos otras cosas mas copadas para
implementar 😛

**Comment by mgarciaisaia** [comment]
Si la única diferencia es el efecto, ¿no tenemos un list_duplicate y lo
implementamos en tres líneas?

**Comment by tferraro** [comment]
No lo veo el list_duplicate, creo que no lo tenemos.

**Comment by gastonprieto** [comment]
Algo así?

```C
t_list* new_list = list_create();
list_add_all(new_list, old_list);
list_sort(new_list, comparer);
return new_list;
```

**Comment by tferraro** [comment]
Exactamente 😁

Si lo ven positivo después le armo un par de test que peguen contra esto

**Comment by gastonprieto** [comment]
dale! solo te va a quedar la parte mas dificil, ponerles nombre :P

**Comment by tferraro** [comment]
list_inmmutable_sort (?)

**Comment by mgarciaisaia** [comment]
Creemos `list_duplicate` que haga `create` + `add_all`, y usemos eso como base para `list_sorted` que crea una nueva lista pero reordenada.

Entonces `list_sort` queda imperativo (_ordenar_), mientras que `list_sorted` es pedir "una lista, pero ordenada así".

**Comment by tferraro** [comment]
+1. Compro

**Comment by mgarciaisaia** [comment]
Ojo que este issue era para un sorted, no para duplicated. Sigue abierto el issue.

**Comment by tferraro** [comment]
Me lo comí y le mandé un "Resolves" sin darme cuenta. Igual mandé un PR con el sorted :wink: 

#NiceCatch

**Comment by gastonprieto** [comment]
Listo, estan las dos cosas en master.
